// <auto-generated />
using System;
using CodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20260313082138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(19,0)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<int?>("SalesRepEmployeeNum")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("SalesRepEmployeeNum");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address1 = "10 Main St",
                            City = "Boston",
                            Country = "USA",
                            CreditLimit = 50000m,
                            FirstName = "Tom",
                            LastName = "Alpha",
                            Name = "Alpha Corp",
                            Phone = "555-1001",
                            PostalCode = 2101,
                            SalesRepEmployeeNum = 3,
                            State = "MA"
                        },
                        new
                        {
                            ID = 2,
                            Address1 = "20 King St",
                            City = "Chicago",
                            Country = "USA",
                            CreditLimit = 30000m,
                            FirstName = "Anna",
                            LastName = "Beta",
                            Name = "Beta LLC",
                            Phone = "555-1002",
                            PostalCode = 60601,
                            SalesRepEmployeeNum = 3,
                            State = "IL"
                        },
                        new
                        {
                            ID = 3,
                            Address1 = "30 Karl St",
                            City = "Berlin",
                            Country = "Germany",
                            CreditLimit = 75000m,
                            FirstName = "Hans",
                            LastName = "Gamma",
                            Name = "Gamma GmbH",
                            Phone = "555-1003",
                            SalesRepEmployeeNum = 4
                        },
                        new
                        {
                            ID = 4,
                            Address1 = "40 Rue St",
                            City = "Lyon",
                            Country = "France",
                            CreditLimit = 40000m,
                            FirstName = "Marie",
                            LastName = "Delta",
                            Name = "Delta SA",
                            Phone = "555-1004",
                            PostalCode = 69001,
                            SalesRepEmployeeNum = 4
                        },
                        new
                        {
                            ID = 5,
                            Address1 = "50 Sakura St",
                            City = "Osaka",
                            Country = "Japan",
                            CreditLimit = 60000m,
                            FirstName = "Yuki",
                            LastName = "Epsilon",
                            Name = "Epsilon Co",
                            Phone = "555-1005",
                            SalesRepEmployeeNum = 5
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Extension")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OfficeCode")
                        .HasColumnType("int");

                    b.Property<int?>("ReportsTo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OfficeCode");

                    b.HasIndex("ReportsTo");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "john@cm.com",
                            Extension = "x101",
                            FirstName = "John",
                            JobTitle = "CEO",
                            LastName = "Smith",
                            OfficeCode = 1
                        },
                        new
                        {
                            ID = 2,
                            Email = "sara@cm.com",
                            Extension = "x102",
                            FirstName = "Sara",
                            JobTitle = "Sales Manager",
                            LastName = "Johnson",
                            OfficeCode = 1,
                            ReportsTo = 1
                        },
                        new
                        {
                            ID = 3,
                            Email = "mike@cm.com",
                            Extension = "x103",
                            FirstName = "Mike",
                            JobTitle = "Sales Rep",
                            LastName = "Brown",
                            OfficeCode = 2,
                            ReportsTo = 1
                        },
                        new
                        {
                            ID = 4,
                            Email = "emily@cm.com",
                            Extension = "x104",
                            FirstName = "Emily",
                            JobTitle = "Sales Rep",
                            LastName = "Davis",
                            OfficeCode = 3,
                            ReportsTo = 2
                        },
                        new
                        {
                            ID = 5,
                            Email = "james@cm.com",
                            Extension = "x105",
                            FirstName = "James",
                            JobTitle = "Sales Rep",
                            LastName = "Wilson",
                            OfficeCode = 4,
                            ReportsTo = 2
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Office", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Territory")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Address1 = "100 Broadway",
                            City = "New York",
                            Country = "USA",
                            Phone = "212-555-0100",
                            PostalCode = 10001,
                            State = "NY"
                        },
                        new
                        {
                            Code = 2,
                            Address1 = "200 Oxford St",
                            City = "London",
                            Country = "UK",
                            Phone = "020-555-0200"
                        },
                        new
                        {
                            Code = 3,
                            Address1 = "300 Champs",
                            City = "Paris",
                            Country = "France",
                            Phone = "033-555-0300",
                            PostalCode = 75001
                        },
                        new
                        {
                            Code = 4,
                            Address1 = "400 Shibuya",
                            City = "Tokyo",
                            Country = "Japan",
                            Phone = "081-555-0400"
                        },
                        new
                        {
                            Code = 5,
                            Address1 = "500 Tahrir Sq",
                            City = "Cairo",
                            Country = "Egypt",
                            Phone = "020-555-0500",
                            PostalCode = 11511
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Comments = "First order",
                            CustomerID = 1,
                            OrderDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequiredDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            Comments = "Urgent",
                            CustomerID = 2,
                            OrderDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequiredDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            Comments = "Pending",
                            CustomerID = 3,
                            OrderDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequiredDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            Comments = "Handle carefully",
                            CustomerID = 4,
                            OrderDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequiredDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            Comments = "Awaiting stock",
                            CustomerID = 5,
                            OrderDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequiredDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Order_product", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("ProductCode")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceEach")
                        .HasColumnType("decimal(19,0)");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ID", "ProductCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("Orders_products");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            ID = 0,
                            ProductCode = 101,
                            PriceEach = 150m,
                            Qty = 2
                        },
                        new
                        {
                            OrderID = 1,
                            ID = 0,
                            ProductCode = 102,
                            PriceEach = 200m,
                            Qty = 1
                        },
                        new
                        {
                            OrderID = 2,
                            ID = 0,
                            ProductCode = 103,
                            PriceEach = 300m,
                            Qty = 3
                        },
                        new
                        {
                            OrderID = 3,
                            ID = 0,
                            ProductCode = 104,
                            PriceEach = 250m,
                            Qty = 1
                        },
                        new
                        {
                            OrderID = 4,
                            ID = 0,
                            ProductCode = 105,
                            PriceEach = 500m,
                            Qty = 2
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Payment", b =>
                {
                    b.Property<string>("CheckNum")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(19,0)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CheckNum");

                    b.HasIndex("CustomerID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            CheckNum = "CHK001",
                            Amount = 300m,
                            CustomerID = 1,
                            PaymentDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CheckNum = "CHK002",
                            Amount = 900m,
                            CustomerID = 2,
                            PaymentDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CheckNum = "CHK003",
                            Amount = 250m,
                            CustomerID = 3,
                            PaymentDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CheckNum = "CHK004",
                            Amount = 1000m,
                            CustomerID = 4,
                            PaymentDate = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CheckNum = "CHK005",
                            Amount = 600m,
                            CustomerID = 5,
                            PaymentDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Product", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(19,0)");

                    b.Property<string>("MSRP")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PdtDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductLineID")
                        .HasColumnType("int");

                    b.Property<int>("QtyInStock")
                        .HasColumnType("int");

                    b.Property<int?>("Scale")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code");

                    b.HasIndex("ProductLineID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Code = 101,
                            BuyPrice = 150m,
                            MSRP = "200",
                            Name = "1969 Mustang",
                            PdtDescription = "Classic muscle car",
                            ProductLineID = 1,
                            QtyInStock = 50,
                            Scale = 18,
                            Vendor = "Ford"
                        },
                        new
                        {
                            Code = 102,
                            BuyPrice = 200m,
                            MSRP = "280",
                            Name = "Harley Davidson",
                            PdtDescription = "Iconic motorcycle",
                            ProductLineID = 2,
                            QtyInStock = 30,
                            Scale = 12,
                            Vendor = "Harley"
                        },
                        new
                        {
                            Code = 103,
                            BuyPrice = 300m,
                            MSRP = "400",
                            Name = "Mack Truck",
                            PdtDescription = "Heavy duty truck",
                            ProductLineID = 3,
                            QtyInStock = 20,
                            Scale = 24,
                            Vendor = "Mack"
                        },
                        new
                        {
                            Code = 104,
                            BuyPrice = 250m,
                            MSRP = "350",
                            Name = "1932 Ford Model B",
                            PdtDescription = "Vintage classic car",
                            ProductLineID = 4,
                            QtyInStock = 15,
                            Scale = 18,
                            Vendor = "Ford"
                        },
                        new
                        {
                            Code = 105,
                            BuyPrice = 500m,
                            MSRP = "700",
                            Name = "Titanic Ship",
                            PdtDescription = "Famous ocean liner",
                            ProductLineID = 5,
                            QtyInStock = 10,
                            Scale = 50,
                            Vendor = "WhiteStar"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.ProductLine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DescinHTML")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DescinText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("ProductLines");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DescinHTML = "<p>Classic Cars</p>",
                            DescinText = "Classic Cars",
                            Image = "classic.jpg"
                        },
                        new
                        {
                            ID = 2,
                            DescinHTML = "<p>Motorcycles</p>",
                            DescinText = "Motorcycles",
                            Image = "moto.jpg"
                        },
                        new
                        {
                            ID = 3,
                            DescinHTML = "<p>Trucks and Buses</p>",
                            DescinText = "Trucks and Buses",
                            Image = "trucks.jpg"
                        },
                        new
                        {
                            ID = 4,
                            DescinHTML = "<p>Vintage Cars</p>",
                            DescinText = "Vintage Cars",
                            Image = "vintage.jpg"
                        },
                        new
                        {
                            ID = 5,
                            DescinHTML = "<p>Ships</p>",
                            DescinText = "Ships",
                            Image = "ships.jpg"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Customer", b =>
                {
                    b.HasOne("CodeFirst.Models.Employee", "Employee")
                        .WithMany("Customers")
                        .HasForeignKey("SalesRepEmployeeNum")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CodeFirst.Models.Employee", b =>
                {
                    b.HasOne("CodeFirst.Models.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeCode")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CodeFirst.Models.Employee", "Manager")
                        .WithMany("Employees")
                        .HasForeignKey("ReportsTo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Manager");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("CodeFirst.Models.Order", b =>
                {
                    b.HasOne("CodeFirst.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CodeFirst.Models.Order_product", b =>
                {
                    b.HasOne("CodeFirst.Models.Order", "Order")
                        .WithMany("Order_Products")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Product", "Product")
                        .WithMany("Order_Products")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CodeFirst.Models.Payment", b =>
                {
                    b.HasOne("CodeFirst.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CodeFirst.Models.Product", b =>
                {
                    b.HasOne("CodeFirst.Models.ProductLine", "ProductLine")
                        .WithMany("Products")
                        .HasForeignKey("ProductLineID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductLine");
                });

            modelBuilder.Entity("CodeFirst.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CodeFirst.Models.Employee", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CodeFirst.Models.Office", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CodeFirst.Models.Order", b =>
                {
                    b.Navigation("Order_Products");
                });

            modelBuilder.Entity("CodeFirst.Models.Product", b =>
                {
                    b.Navigation("Order_Products");
                });

            modelBuilder.Entity("CodeFirst.Models.ProductLine", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
